name: echolip
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip=21.0
  - cudatoolkit=11.3
  - cudnn=8.2
  - numpy=1.19.5
  - scipy=1.7.3
  - matplotlib=3.5.1
  - pandas=1.3.5
  - pillow=8.4.0
  - tqdm=4.62.3
  - pyyaml=6.0
  - pip:
    - torch==1.10.1
    - torchvision==0.11.2
    - torchaudio==0.10.1
    - opencv-python==4.5.5.64
    - face-alignment==1.3.5
    - librosa==0.9.1
    - tensorboard==2.8.0
    - scikit-learn==1.0.2
    - scikit-image==0.19.1
    - pytest==7.0.1
    - black==22.1.0
    - isort==5.10.1
    - flake8==4.0.1
    - pre-commit==2.17.0