data:
  frame_size:
  - 256
  - 256
  train_path: data/datasets/train
  val_path: data/datasets/val
model:
  audio_encoder: conv1d_lstm
  face_encoder: resnet50
  fusion_type: cross_attention
training:
  batch_size: 32
  epochs: 100
  learning_rate: 0.0001
